version: '3.1'

services:
    mongo:
        image: mongo
        volumes:
           - /opt/mongo/data:/data/db
    elasticsearch:
        image: elasticsearch
        volumes:
           - /tmp/:/usr/share/elasticsearch/data
    kibana:
        image: kibana

    scraper:
        image: tincugabriel/news-parser-ro:1.1.1
