version: '3.1'

services:
    mongo:
        image: mongo
        volumes:
           - /opt/mongo/data:/data/db
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
        volumes:
           - /tmp/:/usr/share/elasticsearch/data
    kibana:
        image: kibana

    scraper:
        image: tincugabriel/news-parser-ro:${TAG}
